use crate::{ast, lexer};
use std::borrow::Cow;

grammar<'input>(input: &'input str);

extern {
    type Location = usize;
    type Error = lexer::LexicalError;

    enum lexer::Token<'input> {
        "=" => lexer::Token::Eq,
        "*" => lexer::Token::Multiply,
        "&" => lexer::Token::Ampersand,
        ":" => lexer::Token::Colon,
        ";" => lexer::Token::Semicolon,
        "," => lexer::Token::Comma,
        "." => lexer::Token::Period,
        "..." => lexer::Token::VarArg,

        "(" => lexer::Token::OpenPth,
        ")" => lexer::Token::ClosePth,
        "[" => lexer::Token::OpenBracket,
        "]" => lexer::Token::CloseBracket,
        "{" => lexer::Token::OpenBrace,
        "}" => lexer::Token::CloseBrace,
        "<" => lexer::Token::OpenAngle,
        ">" => lexer::Token::CloseAngle,
        "?" => lexer::Token::QuestionMark,

        Boolean => lexer::Token::Boolean(<bool>),
        Integer => lexer::Token::Integer(<i64>),

        "abstract" => lexer::Token::KeywordAbstract,
        "assert" => lexer::Token::KeywordAssert,
        "break" => lexer::Token::KeywordBreak,
        "case" => lexer::Token::KeywordCase,
        "catch" => lexer::Token::KeywordCatch,
        "class" => lexer::Token::KeywordClass,
        "continue" => lexer::Token::KeywordContinue,
        "const" => lexer::Token::KeywordConst,
        "default" => lexer::Token::KeywordDefault,
        "do" => lexer::Token::KeywordDo,
        "else" => lexer::Token::KeywordElse,
        "enum" => lexer::Token::KeywordEnum,
        "exports" => lexer::Token::KeywordExports,
        "extends" => lexer::Token::KeywordExtends,
        "final" => lexer::Token::KeywordFinal,
        "finally" => lexer::Token::KeywordFinally,
        "for" => lexer::Token::KeywordFor,
        "goto" => lexer::Token::KeywordGoto,
        "if" => lexer::Token::KeywordIf,
        "implements" => lexer::Token::KeywordImplements,
        "import" => lexer::Token::KeywordImport,
        "instanceof" => lexer::Token::KeywordInstanceof,
        "interface" => lexer::Token::KeywordInterface,
        "module" => lexer::Token::KeywordModule,
        "native" => lexer::Token::KeywordNative,
        "new" => lexer::Token::KeywordNew,
        "non-sealed" => lexer::Token::KeywordNonSealed,
        "package" => lexer::Token::KeywordPackage,
        "permits" => lexer::Token::KeywordPermits,
        "private" => lexer::Token::KeywordPrivate,
        "protected" => lexer::Token::KeywordProtected,
        "public" => lexer::Token::KeywordPublic,
        "record" => lexer::Token::KeywordRecord,
        "requires" => lexer::Token::KeywordRequires,
        "return" => lexer::Token::KeywordReturn,
        "sealed" => lexer::Token::KeywordSealed,
        "static" => lexer::Token::KeywordStatic,
        "strictfp" => lexer::Token::KeywordStrictfp,
        "super" => lexer::Token::KeywordSuper,
        "switch" => lexer::Token::KeywordSwitch,
        "synchronized" => lexer::Token::KeywordSynchronized,
        "this" => lexer::Token::KeywordThis,
        "throw" => lexer::Token::KeywordThrow,
        "throws" => lexer::Token::KeywordThrows,
        "transient" => lexer::Token::KeywordTransient,
        "try" => lexer::Token::KeywordTry,
        "var" => lexer::Token::KeywordVar,
        "volatile" => lexer::Token::KeywordVolatile,
        "while" => lexer::Token::KeywordWhile,

        "void" => lexer::Token::TypeVoid,
        "boolean" => lexer::Token::TypeBoolean,
        "byte" => lexer::Token::TypeByte,
        "char" => lexer::Token::TypeChar,
        "short" => lexer::Token::TypeShort,
        "int" => lexer::Token::TypeInt,
        "long" => lexer::Token::TypeLong,
        "float" => lexer::Token::TypeFloat,
        "double" => lexer::Token::TypeDouble,

        RecordCtor => lexer::Token::RecordCtor,

        String => lexer::Token::String(<Cow<'input, str>>),
        Ident => lexer::Token::Ident(<Cow<'input, str>>),
    }
}

#[inline]
IdentName: &'input str = <l:@L> Ident <r:@R> => &input[l..r];

#[inline]
UnsafeIdent: &'input str = {
  <l:@L> Ident <r:@R> => &input[l..r],
  <l:@L> "module" <r:@R> => &input[l..r],
  <l:@L> "this" <r:@R> => &input[l..r],
  <l:@L> "record" <r:@R> => &input[l..r],
  <l:@L> "sealed" <r:@R> => &input[l..r],
  <l:@L> "var" <r:@R> => &input[l..r],
  <l:@L> "exports" <r:@R> => &input[l..r],
  <l:@L> "requires" <r:@R> => &input[l..r],
  <l:@L> "permits" <r:@R> => &input[l..r],
};

#[inline]
Path: &'input str = <l:@L> UnsafeIdent ("." UnsafeIdent)* <r:@R> => &input[l..r];

CommaList<T>: Box<[T]> = <mut items:(<T> ",")*> <last:T> => { items.push(last); items.into_boxed_slice() };
TrailingCommaList<T>: Box<[T]> = <items:(<T> ",")+> => items.into_boxed_slice();

OptionalSemicolonList<T>: Box<[T]> = <items:(<T> ";"*)+> => items.into_boxed_slice();

MayBeTrailingCommaList<T>: Box<[T]> = {
  <CommaList<T>> => <>,
  <TrailingCommaList<T>> => <>,
};

AmpersandList<T>: Box<[T]> = <mut items:(<T> "&")*> <last:T> => { items.push(last); items.into_boxed_slice() };
PeriodList<T>: Box<[T]> = <mut items:(<T> ".")*> <last:T> => { items.push(last); items.into_boxed_slice() };

Package: &'input str = "package" <p:Path> ";"+ => p;

#[inline]
ImportPath: &'input str = <l:@L> UnsafeIdent ("." UnsafeIdent)* ("." "*")? <r:@R> => &input[l..r];
Import: &'input str = "import" "static"? <p:ImportPath> ";"+ => p;

Modifier: ast::Modifiers = {
  "public" => ast::Modifiers::PUBLIC,
  "private" => ast::Modifiers::PRIVATE,
  "protected" => ast::Modifiers::PROTECTED,
  "static" => ast::Modifiers::STATIC,
  "final" => ast::Modifiers::FINAL,
  "sealed" => ast::Modifiers::SEALED,
  "non-sealed" => ast::Modifiers::NON_SEALED,
  "abstract" => ast::Modifiers::ABSTRACT,
  "native" => ast::Modifiers::NATIVE,
  "synchronized" => ast::Modifiers::SYNCHRONIZED,
  "transient" => ast::Modifiers::TRANSIENT,
  "volatile" => ast::Modifiers::VOLATILE,
  "strictfp" => ast::Modifiers::STRICTFP,
  "default" => ast::Modifiers::DEFAULT,
}

Modifiers: ast::Modifiers = {
  => ast::Modifiers::empty(),
  <modifier:Modifier> <modifiers:Modifiers> => modifier | modifiers,
};

ArraySuffix: usize = {
  => 0,
  "[" "]" <depth:ArraySuffix> => depth + 1,
};

PrimitiveType: ast::Type<'input> = {
  "void" => ast::Type::Void,
  "boolean" => ast::Type::Boolean,
  "byte" => ast::Type::Byte,
  "char" => ast::Type::Char,
  "short" => ast::Type::Short,
  "int" => ast::Type::Integer,
  "long" => ast::Type::Long,
  "float" => ast::Type::Float,
  "double" => ast::Type::Double,
};

TypeGeneric: ast::GenericImpl<'input> = {
  <t:QualifiedType>               => ast::GenericImpl::Type(t),
  "?"                             => ast::GenericImpl::Wildcard(ast::GenericWildcardBoundary::None),
  "?" "extends" <t:QualifiedType> => ast::GenericImpl::Wildcard(ast::GenericWildcardBoundary::Extends(t)),
  "?" "super" <t:QualifiedType>   => ast::GenericImpl::Wildcard(ast::GenericWildcardBoundary::Super(t)),
};

pub TypeGenerics: Box<[ast::GenericImpl<'input>]> = "<" <l:CommaList<TypeGeneric>?> ">" => l.unwrap_or(Box::from([]));

Type: ast::Type<'input> = {
  <t:PrimitiveType> <a:ArraySuffix>
  => ast::TypeBuilder::any(t).wrap_by_array(a).build(),

  <n:IdentName> <g:TypeGenerics?> <a:ArraySuffix>
  => ast::TypeBuilder::named(n)
    .with_generic_impls(g.unwrap_or(Box::from([])))
    .wrap_by_array(a)
    .build(),
  };

QualifiedType: ast::QualifiedType<'input>
  = <items:PeriodList<Type>>
  => ast::QualifiedTypeBuilder::new(items).build();

#[inline]
UnsafeIdentWithArray: (&'input str, usize)
  = <i:UnsafeIdent> <a:ArraySuffix>
  => (i, a);

Fields: Box<[ast::Field<'input>]>
  = <m:Modifiers> <t:QualifiedType> <i:CommaList<UnsafeIdentWithArray>> ";"
  => {
    let mut names = i.into_vec();
    let mut fields = Vec::with_capacity(names.len());
    let mut base_modifiers = Some(m);
    let mut base_type = Some(t);

    while let Some((name, array_depth)) = names.pop() {
      let modifiers = if names.is_empty() {
        base_modifiers.take().unwrap()
      } else {
        base_modifiers.as_ref().unwrap().clone()
      };
      let ty = if names.is_empty() {
        base_type.take().unwrap()
      } else {
        base_type.as_ref().unwrap().clone()
      };

      fields.push(
        ast::FieldBuilder::single(name)
          .with_modifiers(modifiers)
          .with_type(
            ast::QualifiedTypeBuilder::new(ty)
              .with_array_depth(array_depth)
              .build()
          )
          .build()
      );
    }

    fields.reverse();
    fields.into_boxed_slice()
  };

GenericDefinitionsExtends: Box<[ast::QualifiedType<'input>]> = "extends" <e:AmpersandList<QualifiedType>> => e;

GenericDefinition: ast::GenericDecl<'input>
  = <i:IdentName> <e:GenericDefinitionsExtends?>
  => ast::GenericDeclBuilder::new(i)
    .with_extends(e.unwrap_or(Box::new([])))
    .build();

GenericDefinitions: Box<[ast::GenericDecl<'input>]>
  = "<" <g:CommaList<GenericDefinition>> ">"
  => g;

FunctionArgument: ast::FunctionArgument<'input>
  = <m:Modifiers> <t:QualifiedType> <v:"..."?> <i:UnsafeIdent> <a:ArraySuffix>
  => {
    let builder = ast::FunctionArgumentBuilder::new(i)
      .with_modifiers(m)
      .with_type(
        ast::QualifiedTypeBuilder::new(t)
          .with_array_depth(a)
          .build()
      );

    if v.is_some() {
      builder.with_vararg().build()
    } else {
      builder.build()
    }
  };

RecordField: ast::Field<'input>
  = <arg:FunctionArgument>
  => ast::FieldBuilder::single(arg.name)
    .with_modifiers(arg.modifiers)
    .with_type(arg.r#type)
    .build();

#[inline]
FunctionEnd: () = { "{" "}" => (), ";" => () };

#[inline]
FunctionReturnArraySuffix: usize = <a:ArraySuffix> => a;

Function: ast::Function<'input>
  = <m:Modifiers> <g:GenericDefinitions?> <rt:QualifiedType> <i:UnsafeIdent?> "(" <args:CommaList<FunctionArgument>?> ")" <a:FunctionReturnArraySuffix> ("throws" CommaList<QualifiedType>)? FunctionEnd
  => ast::FunctionBuilder::new(i.unwrap_or("__ctor"))
      .with_modifiers(m)
      .with_generic_decls(g.unwrap_or(Box::from([])))
      .with_return_type(
        ast::QualifiedTypeBuilder::new(rt)
          .with_array_depth(a)
          .build()
      )
      .with_args(args.unwrap_or(Box::from([])))
      .build();

InterfaceEntry: ast::InterfaceEntry<'input> = {
  <v:Fields> => ast::InterfaceEntry::Fields(v),
  <f:Function> => ast::InterfaceEntry::Function(f),
  <c:Class> => ast::InterfaceEntry::Class(c),
  <e:Enum> => ast::InterfaceEntry::Enum(e),
  <i:Interface> => ast::InterfaceEntry::Interface(i),
  "static"? "{" "}" => ast::InterfaceEntry::Skip,
  Modifiers RecordCtor "{" "}" => ast::InterfaceEntry::Skip,
};

#[inline]
ObjectPermits: Box<[ast::QualifiedType<'input>]> = "permits" <l:CommaList<QualifiedType>> => l;

#[inline]
InterfaceExtends: Box<[ast::QualifiedType<'input>]> = "extends" <t:CommaList<QualifiedType>> => t;

Interface: ast::Interface<'input>
  = <m:Modifiers> "interface" <i:IdentName> <g:GenericDefinitions?> <ex:InterfaceExtends?> <p:ObjectPermits?> "{" <e:OptionalSemicolonList<InterfaceEntry>?> "}"
  => ast::InterfaceBuilder::new(i)
    .with_modifiers(m)
    .with_generic_decls(g.unwrap_or(Box::from([])))
    .with_extends(ex.unwrap_or(Box::from([])))
    .with_permits(p.unwrap_or(Box::from([])))
    .with_entries(e.unwrap_or(Box::from([])))
    .build();

#[inline]
ObjectImplements: Box<[ast::QualifiedType<'input>]> = "implements" <l:CommaList<QualifiedType>> => l;

ClassEntry: ast::ClassEntry<'input> = {
  <v:Fields> => ast::ClassEntry::Fields(v),
  <f:Function> => ast::ClassEntry::Function(f),
  <c:Class> => ast::ClassEntry::Class(c),
  <e:Enum> => ast::ClassEntry::Enum(e),
  <i:Interface> => ast::ClassEntry::Interface(i),
  "static"? "{" "}" => ast::ClassEntry::Skip,
  Modifiers RecordCtor "{" "}" => ast::ClassEntry::Skip,
};

#[inline]
ClassExtends: ast::QualifiedType<'input> = "extends" <t:QualifiedType> => t;

Class: ast::Class<'input> = {
  <m:Modifiers> "class" <i:IdentName> <g:GenericDefinitions?> <ex:ClassExtends?> <im:ObjectImplements?> <p:ObjectPermits?> "{" <en:OptionalSemicolonList<ClassEntry>?> "}"
  => {
    let builder = ast::ClassBuilder::class(i)
      .with_modifiers(m)
      .with_generic_decls(g.unwrap_or(Box::from([])))
      .with_implements(im.unwrap_or(Box::from([])))
      .with_permits(p.unwrap_or(Box::from([])))
      .with_entries(en.unwrap_or(Box::from([])));

    if let Some(ex) = ex {
      builder.with_extend(ex).build()
    } else {
      builder.build()
    }
  },

  <m:Modifiers> "record" <i:IdentName> <g:GenericDefinitions?> "(" <a:CommaList<RecordField>?> ")" <im:ObjectImplements?> "{" <en:OptionalSemicolonList<ClassEntry>?> "}"
  => ast::ClassBuilder::record(i, a.unwrap_or(Box::from([])))
    .with_modifiers(m)
    .with_generic_decls(g.unwrap_or(Box::from([])))
    .with_implements(im.unwrap_or(Box::from([])))
    .with_entries(en.unwrap_or(Box::from([])))
    .build(),
};

#[inline]
EnumVariant: () = IdentName ("(" ")")? ("{" "}")?;

#[inline]
EnumEntry: ast::EnumEntry<'input> = {
  <v:Fields> => ast::EnumEntry::Fields(v),
  <f:Function> => ast::EnumEntry::Function(f),
  <c:Class> => ast::EnumEntry::Class(c),
  <e:Enum> => ast::EnumEntry::Enum(e),
  <i:Interface> => ast::EnumEntry::Interface(i),
  "static"? "{" "}" => ast::EnumEntry::Skip,
};

#[inline]
EnumBody: Box<[ast::EnumEntry<'input>]> = {
  MayBeTrailingCommaList<EnumVariant> ";"?             => Box::from([]),
  MayBeTrailingCommaList<EnumVariant> ";" <OptionalSemicolonList<EnumEntry>> => <>,
};

Enum: ast::Enum<'input>
  = <m:Modifiers> "enum" <i:IdentName> <g:GenericDefinitions?> <im:ObjectImplements?> "{" <b:EnumBody?> "}"
  => ast::EnumBuilder::new(i)
    .with_modifiers(m)
    .with_generic_decls(g.unwrap_or(Box::from([])))
    .with_implements(im.unwrap_or(Box::from([])))
    .with_entries(b.unwrap_or(Box::from([])))
    .build();

RootEntry: ast::RootEntry<'input> = {
  <c:Class> => ast::RootEntry::Class(c),
  <e:Enum> => ast::RootEntry::Enum(e),
  <i:Interface> => ast::RootEntry::Interface(i),
};

pub Root: ast::Root<'input>
  = <p:Package> <i:Import*> <e:OptionalSemicolonList<RootEntry>?>
  => {
    let mut imports = i;
    imports.push("java.lang.*");

    ast::RootBuilder::new(p)
      .with_imports(imports)
      .with_entries(e.unwrap_or(Box::from([])))
      .build()
  };
