[package]
name = "java2pyi"
version = "2.0.1"
edition = "2024"
license = "MIT"
keywords = ["java", "jar", "codegen"]
categories = ["command-line-utilities"]
description = "Java class files to Python stubs for mypy/pyright"
repository = "https://github.com/n08i40k/java2pyi"
readme = "README.md"

[dependencies]
anyhow = "1.0.104"
bitflags = "2.11.1"
bumpalo = { version = "3.20.3", features = ["collections"] }
env_logger = "0.11.10"
jvm-class = "0.1.0"
memmap2 = "0.9.11"
orx-tree = "2.2.0"
rayon = "1.12.0"
tempfile = "3.27.0"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
